### ISSUE TITLE
extractSubList(xs, ..., simplify=TRUE) returns a list() if xs is empty

### ISSUE THREAD

**Issue by mb706** [berndbischl/BBmisc#55]
I sometimes use `extractSubList` with `simplify=TRUE` as an index into another vector/list:
```R
named_vector[extractSubList(someList, "names")]
```
This fails in the corner-case when `someList` is empty, since `extractSubList` returns a `list()` in that case. This could be fixed by returning some empty vector or `NULL` in that case (and if `simplify == TRUE`).

`NULL` seems like a good idea at first, but I would argue against it since returning `NULL` can be dangerous when the user doesn't expect it (`x$abc = 1; x$a = unexpected_null() ; x$a` gives 1). I would suggest `raw(0)` or `logical(0)`.

**Comment by berndbischl** [comment]
But sapply also returns an empty list. So out of consistency....
And I do have to say that I find the empty list most logical?

**Comment by berndbischl** [comment]
Thought about somemore. I guess we cannot do this (I do appreciate the discussion though).
Arguments:

1) This is an API change that can possibly break code in other places. This alone seems to rule it out.

2) Like I said in the post above, we would not even "fix something", but basically move "away" from behavior that is already consistent with R. 

3) Now 1) and 2) together are pretty strong. And your argument against this is basically: 
"It is does not work in the specific case I am using it".
I do know that these things in R are not always very well defined, and some of the special cases suck. 
But here I am kinda sure that I _like_ the empty list? I mean I dont really see why the simplification of the empty list should be logical(0). Thats actually possibly something that I _would_ be annoyed about in R, if it would be done behind my back.

I will close this, complain and reopen if you think I am wrong.
