### ISSUE TITLE
Make coalesce's documentation more clear about it swallowing errors

### ISSUE THREAD

**Issue by mb706** [berndbischl/BBmisc#56]
``` R
> coalesce(stop("I will die before I return NULL"))
NULL
```

... surprised me. This is a bit of a problem when someone uses `coalesce` together with a function call that never returns `NULL` but which may fail, and then expects the return of `coalesce` to be non-`NULL`.

**Comment by berndbischl** [comment]
ok i am not proud of this function, and i dislike heavily how we implemented this. 
but i currently dont know how to fix this. 
 
as you suggested, i just improved docs

#' We have to perform some pretty weird \code{\link{tryCatch}} stuff internally,
#' so you should better not pass complex function calls into the arguments that can throw exceptions,
#' as these will be completely muffled, and return \code{NULL} in the end.
