### ISSUE TITLE
namedList with no args should really be named

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/BBmisc#58]
currently it simply creates list() but not namedList

**Comment by jakobbossek** [comment]
Hmm, how do you want to realize this?
How to name an empty list?

**Comment by berndbischl** [comment]
x = setNames(list(), character(0))

that is (unfortunately?) not the same as list()

in R you can create an empty list, which is a "named list". 
look at both objects with str()

and:

for names(list()) the result is NULL, for the code in the 1st line it is char(0)

**Comment by berndbischl** [comment]
@jakob-r already fixed this, i clarified docs
