### ISSUE TITLE
convertListOfRowsToDataFrame converts NULL to NA

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/BBmisc#68]
``` r
> BBmisc::convertListOfRowsToDataFrame(list(list(a = 1, b = NULL)))
  a  b
1 1 NA
```

I know, that a NULL in a data.frame cell is not verry common. But we could issue a warning about this conversion.

**Comment by berndbischl** [comment]
well the docs said that "missing values" are encoded as NA in the result. 
"missing" here meaning: not in the list.

NULL is basically the same thing. i will just update docs and add a few tests for this.
i think this is actually good, consistent behavior.

and warnings suck.

**Comment by berndbischl** [comment]
did what i said
