### ISSUE TITLE
Can we have valueToString in BBmisc?

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/BBmisc#69]
This function could be usefull in BBmisc. What do you think? https://github.com/berndbischl/ParamHelpers/blob/c0013d7ff91b478111aed437930aeb0aaa951f50/R/paramValueToString.R#L82

**Comment by berndbischl** [comment]
we do have convertToShortString, doesnt this have the same goal?

**Comment by jakob-r** [comment]
So you suggest to remove valueToString and to improve convertToShortString?

**Comment by berndbischl** [comment]
> So you suggest to remove valueToString and to improve convertToShortString?

i think so
