### ISSUE TITLE
convertToShortString(list()) is ""

### ISSUE THREAD

**Issue by mb706** [berndbischl/BBmisc#74]
```R
> convertToShortString(list())
[1] ""
```
It might be more useful to have a `list()` or something, similarly to how other empty vectors are handled.

**Comment by jakob-r** [comment]
The function name tells you, that it will return a string. It would be confusing to suddenly have an empty list as a result and it can also break things if you rely on having  a string as a result. We could discuss if `character(0)` was a better return value.

**Comment by berndbischl** [comment]
either "()" or "<empty list>" or "list()"

can you do a PR an maybe also check empty vectors?
