### ISSUE TITLE
optimizeSubInts: What if res$objective is NA

### ISSUE THREAD

**Issue by MinhAnhL** [berndbischl/BBmisc#78]
@berndbischl 
I'm currently working in mlr on a new class "oneclass".  Now I'm doing nested resampling with threshold tuning to test the algorithm.
I sometimes get an error in optimizeSubInts() in tuneThreshold.R (in mlr).

>  Error in if (mult * res$objective < mult * best$objective) best = res : 
>   missing value where TRUE/FALSE needed 

the problem ist` res$objective` is `NA`. Is there a way to handle this situation?

If a draw again new resample instances the error occur in a later tuning step.

**Comment by MinhAnhL** [comment]
I is because of the combination of the svm-algo, oneclass cross validation (traindata only contain normal data) and the f1 measure and the data.
At least I don't get this error when using another measure instead of f1.

**Comment by berndbischl** [comment]
well,
1) i cannot help if there is not a reproducible example
2) optimizeSubints is just a very thin wrapper around "optimize" - and that simply cannot handle NAs in the objective - as most optimizers
3) your best option is to create a full example, in the mlr tracker, that demos that f1 can become NA. that the most likely fix
