### ISSUE TITLE
normalize function giving error

### ISSUE THREAD

**Issue by boseb** [berndbischl/BBmisc#86]
Hi, I am normalizing a dataframe but normalize function is giving error
> x<- matrix(1:9,3,3)
> x
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
> normalize(x, method = "standardize", range = c(0, 1), margin = 2L, on.constant = "quiet")
**Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘normalize’ for signature ‘"matrix"’**

please help

**Comment by berndbischl** [comment]
There is a very clear error message which you simply need to read? Hint. You are not passing a Df.
